<meta name="csrf-token" content="{{ csrf_token() }}">

@extends('layouts.app')

@include('inc._jumbotron')


@section('content')
<div class="d-flex m-3">
  <div class="row">
    <!-- <div class="col-lg-12"> -->
      <div class="col-2">@include('inc._sidebar')</div>
          <div class="col-lg-10">
            <h1 style="font-family: Freckle Face;">Biography</h1>
            </p>THE GRIM STARTED IN 1982 PLAYING PARTIES IN THE SAN FERNANDO VALLEY. THEIR MUSIC APPEARED ON NUMEROUS COMPILATION RECORDS RELEASED BY MYSTIC RECORDS. IN 1984 MYSTIC RELEASED THEIR SELF TITLED RECORD KNOWN AS THE "ORANGE ALBUM". YOU MAY HAVE SEEN IT AS A BACKDROP IN THE MOVIE "PRETTY IN PINK". THE GRIM TOURED THE COUNTRY WITH NOFX, SCARED STRAIGHT. THEY PLAYED WITH BANDS LIKE SOCIAL DISTORTION, BAD RELIGION, NOFX, MINUTEMEN, PENNYWISE, THE VANDALS, DESCENDANTS, FACE TO FACE, RKL, NO USE FOR A NAME, ILL REPUTE, CIRCLE JERKS, AND MANY MORE! THE SONG, "SAIPAN DEATH MARCH" WAS ONE OF THE MOST REQUESTED SONGS ON THE RODNEY ON THE ROQ SHOW IN 1984. IN 1986 MYSTIC RECORDS RELEASED A SUPER SEVEN INCH RECORD FEATURING 4 SONGS RECORDED IN A TELEVISION STUDIO, ENTITLED "LIVE TO DIE". IN 1987 THE GRIM RECORDED AN ALBUM FOR MYSTIC THAT WAS EVENTUALLY RELEASED ON ALCHEMY RECORDS CALLED FACE OF BETRAYAL. IN 1988 MYSTIC RELEASED THE 7" LIVE AT FENDERS.
            THE BAND ENDED IN THE MID 90'S WHEN TIM STARTED WORKING FOR NOFX. THE BAND DID A COUPLE OF REUNION SHOWS IN EARLY 2001 WITH THE ORIGINAL MEMBERS, BUT SINCE JORDAN WAS IN STRUNG OUT THE REUNION WAS SHORT LIVED.
            FAST FORWARD TO 2010 THE BAND REFORMED WITH 3 NEW MEMBERS. TIM WAS ALWAYS TALKING WITH WITH EX JUGHEAD'S REVENGE BASSIST BRIAN PREISS ABOUT STARTING UP A NEW BAND, BUT BRIAN CONVINCED HIM TO REFORM THE GRIM. WHEN HE DECIDED TO CALL BOB, HE AGREED TO DO THE GRIM ONE MORE TIME.
            JEFF YEARSLEY WAS ASKED TO PLAY 2ND GUITAR. JEFF WAS A FELLOW BAND MATE AND FRIEND OF BRIAN'S FROM THE EARLY PUNK ROCK DAYS. THE BAND PLAYED THEIR FIRST SHOW WITH THE NEW LINE UP OPENING UP FOR THE ADOLESCENTS IN THE SUMMER OF 2010. 2016 SAW THE ADDITION OF ONE OF SIMI VALLEY'S FINEST DRUMMERS, MICAH ROSSELLINI. THE BAND WAS NOW COMPLETE AND IN 2017 RELEASED A NEW 7" ON FELONY RECORDS. IN 2018, THE BAND IS SET TO RELEASE THEIR FIRST FULL LENTH VINYL IN 30 YEARS WITH NEW WORLD ORDER THROUGH SOUND SPEED RECORDS.
            </p>
          </div>
      <!-- </div> -->
    </div>
  </div>
@endsection

@include('inc._footer')
