<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
  public function run()
    {
       DB::table('posts')->truncate();

       $posts = [
            ['title' => 'Bacon Blog', 'post' => string addslashes('Bacon ipsum dolor amet pancetta doner venison andouille tri-tip spare ribs turducken picanha alcatra tail, pork belly flank hamburger. Hamburger tri-tip bresaola chuck tenderloin turducken corned beef capicola sirloin buffalo. Meatloaf corned beef ribeye pig. Flank ribeye jowl pork belly shank beef ribs pastrami porchetta pig filet mignon cupim doner bresaola chuck.<br>
            Ball tip pork chop buffalo kevin meatball tenderloin brisket rump. Shoulder biltong corned beef, ham hock venison turducken pork chop frankfurter chuck burgdoggen pork doner ground round pastrami. Tongue meatloaf bacon pork chop, salami t-bone filet mignon pork belly tenderloin jerky sausage pork pancetta short ribs capicola. Pig venison cow tongue, prosciutto shankle pork belly pork chop alcatra t-bone pork filet mignon chuck.')],

            ['title' => 'Cat Blog', 'post' => string addslashes('Chirp at birds chew the plant. Cough run up and down stairs. Make meme, make cute face flop over, or cry louder at reflection eat a rug and furry furry hairs everywhere oh no human coming lie on counter don't get off counter scratch the postman wake up lick paw wake up owner meow meow so howl on top of tall thing. Decide to want nothing to do with my owner today instantly break out into full speed gallop across the house for no reason and roll on the floor purring your whiskers off or run outside as soon as door open so mark territory, or make plans to dominate world and then take a nap so meow. Push your water glass on the floor. Rub face on owner knock over christmas tree immediately regret falling into bathtub vommit food and eat it again. Ask to go outside and ask to come inside and ask to go outside and ask to come inside. Flex claws on the human's belly and purr like a lawnmower destroy house in 5 seconds but pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now yet run around the house at 4 in the morning, scoot butt on the rug. Howl on top of tall thing give me some of your food give me some of your food give me some of your food meh, i don't want it, cat slap dog in face and meow for food, then when human fills food dish, take a few bites of food and continue meowing and playing with balls of wool. Lick butt and make a weird face when owners are asleep, cry for no apparent reason for scratch the box groom yourself 4 hours - checked, have your beauty sleep 18 hours - checked, be fabulous for the rest of the day - checked and annoy the old grumpy cat, start a fight and then retreat to wash when i lose this human feeds me, i should be a god. Stand with legs in litter box, but poop outside tickle my belly at your own peril i will pester for food when you're in the kitchen even if it's salad yet human give me attention meow so chase red laser dot. Burrow under covers when owners are asleep, cry for no apparent reason or bleghbleghvomit my furball really tie the room together for twitch tail in permanent irritation and put butt in owner's face. Knock over christmas tree leave dead animals as gifts, and munch, munch, chomp, chomp sweet beast. Stare at guinea pigs refuse to leave cardboard box stares at human while pushing stuff off a table meow for meow dont wait for the storm to pass, dance in the rain. Cuddle no cuddle cuddle love scratch scratch meow to be let out. Leave hair everywhere refuse to leave cardboard box so that box? i can fit in that box destroy couch as revenge. Sniff sniff cat is love, cat is life scratch the box attack the child always ensure to lay down in such a manner that tail can lightly brush human's nose . Who's the baby cat not kitten around.<br>
            Loved it, hated it, loved it, hated it shove bum in owner's face like camera lens. Brown cats with pink ears see owner, run in terror eat plants, meow, and throw up because i ate plants. Sit on human eat plants, meow, and throw up because i ate plants for the door is opening! how exciting oh, it's you, meh so then cats take over the world. Catch mouse and gave it as a present attack feet. Jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed russian blue yet stares at human while pushing stuff off a table so paw at beetle and eat it before it gets away mrow pushes butt to face, cat fur is the new black . Touch my tail, i shred your hand purrrr loved it, hated it, loved it, hated it for eat from dog's food and rub face on owner, for ears back wide eyed. Man running from cops stops to pet cats, goes to jail chew foot. Sit in a box for hours it's 3am, time to create some chaos . Ask to be pet then attack owners hand eat the fat cats food chase dog then run away for kitty scratches couch bad kitty yet meowing non stop for food roll over and sun my belly scream at teh bath. Playing with balls of wool sleep on keyboard kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff, meow that box?')],

            ['title' => 'Star Wars Blog', 'post' => string addslashes('No! Alderaan is peaceful. We have no weapons. You can\'\t possibly… I care. So, what do you think of her, Han? The Force is strong with this one. I have you now. The more you tighten your grip, Tarkin, the more star systems will slip through your fingers.<br>
            Hokey religions and ancient weapons are no match for a good blaster at your side, kid. I can't get involved! I\'\ve got work to do! It\'\s not that I like the Empire, I hate it, but there's nothing I can do about it right now. It's such a long way from here.<br>
            I\'\m surprised you had the courage to take the responsibility yourself. Ye-ha! I have traced the Rebel spies to her. Now she is my only link to finding their secret base. You mean it controls your actions?<br>
            Partially, but it also obeys your commands. A tremor in the Force. The last time I felt it was in the presence of my old master. In my experience, there is no such thing as luck. In my experience, there is no such thing as luck.<br>
            Escape is not his plan. I must face him, alone. I care. So, what do you think of her, Han? I have traced the Rebel spies to her. Now she is my only link to finding their secret base. I find your lack of faith disturbing.<br>
            Remember, a Jedi can feel the Force flowing through him. Your eyes can deceive you. Don't trust them. I suggest you try it again, Luke. This time, let go your conscious self and act on instinct. What good is a reward if you ain't around to use it? Besides, attacking that battle station ain't my idea of courage. It's more like…suicide.<br>
            I call it luck. No! Alderaan is peaceful. We have no weapons. You can't possibly… Hokey religions and ancient weapons are no match for a good blaster at your side, kid. I'm trying not to, kid. Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money.<br>
            Red Five standing by. I can't get involved! I've got work to do! It's not that I like the Empire, I hate it, but there's nothing I can do about it right now. It's such a long way from here. As you wish.')],

            ['title' => 'Monty Python Post', 'post' => string addslashes('Who's that then? We found them. The swallow may fly south with the sun, and the house martin or the plover may seek warmer climes in winter, yet these are not strangers to our land. Oh, ow! I am your king.<br>
            The swallow may fly south with the sun, and the house martin or the plover may seek warmer climes in winter, yet these are not strangers to our land. Shut up! Burn her anyway! We found them. Bloody Peasant!<br>
            We found them. We want a shrubbery!! I dunno. Must be a king. Did you dress her up like this?<br>
            I dunno. Must be a king. I don't want to talk to you no more, you empty-headed animal food trough water! I fart in your general direction! Your mother was a hamster and your father smelt of elderberries! Now leave before I am forced to taunt you a second time!<br>
            Burn her anyway! Well, how'd you become king, then? The Knights Who Say Ni demand a sacrifice! And the hat. She's a witch! He hasn't got shit all over him. Shut up! Will you shut up?!<br>
            Did you dress her up like this? Found them? In Mercia?! The coconut's tropical! He hasn't got shit all over him. Found them? In Mercia?! The coconut's tropical! I have to push the pram a lot.<br>
            Well, we did do the nose. Now, look here, my good man. Why do you think that she is a witch? She looks like one. You don't vote for kings.<br>
            But you are dressed as one… She looks like one. Well, Mercia's a temperate zone! Shut up! Will you shut up?!<br>
            …Are you suggesting that coconuts migrate? The swallow may fly south with the sun, and the house martin or the plover may seek warmer climes in winter, yet these are not strangers to our land. Burn her anyway!<br>
            What do you mean? Well, I didn't vote for you. Knights of Ni, we are but simple travelers who seek the enchanter who lives beyond these woods. You don't frighten us, English pig-dogs! Go and boil your bottoms, sons of a silly person! I blow my nose at you, so-called Ah-thoor Keeng, you and all your silly English K-n-n-n-n-n-n-n-niggits!<br>
            Oh! Come and see the violence inherent in the system! Help, help, I'm being repressed! The Knights Who Say Ni demand a sacrifice! What a strange person. The Knights Who Say Ni demand a sacrifice! A newt?
            ')],

            ['title' => 'Bob Ross Blog', 'post' => string addslashes('I really recommend you use odorless thinner or your spouse is gonna run you right out into the yard and you'll be working by yourself. If what you're doing doesn't make you happy - you're doing the wrong thing. Sometimes you learn more from your mistakes than you do from your masterpieces. That's a son of a gun of a cloud. Only think about one thing at a time. Don't get greedy.<br>
            I like to beat the brush. God gave you this gift of imagination. Use it. Isn't that fantastic that you can create an almighty tree that fast? Everyone is going to see things differently - and that's the way it should be. We'll put all the little clouds in and let them dance around and have fun.<br>
            We can fix anything. Just let this happen. We just let this flow right out of our minds. All you need to paint is a few tools, a little instruction, and a vision in your mind. I spend a lot of time walking around in the woods and talking to trees, and squirrels, and little rabbits and stuff.<br>
            You can do anything your heart can imagine. I want everbody to be happy. That's what it's all about. We'll put a happy little bush here. That is when you can experience true joy, when you have no fear.<br>
            You can get away with a lot. You are only limited by your imagination. Trees cover up a multitude of sins.<br>
            There he comes. Just go out and talk to a tree. Make friends with it. Trees live in your fan brush, but you have to scare them out. Don't hurry. Take your time and enjoy.<br>
            The only prerequisite is that it makes you happy. If it makes you happy then it's good. Just beat the devil out of it. In your world you can create anything you desire. There isn't a rule. You just practice and find out which way works best for you.')],

            ['title' => 'Samuel L. Jackson Blog', 'post' =>
            strings addslashes('Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'<br>
            Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.<br>
            Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.<br>')],

            ['title' => 'The Office Blog', 'post' => string addslashes('High touch client. Pipeline. Guerrilla marketing gain traction powerPointless, for what do you feel you would bring to the table if you were hired for this position, or pipeline, yet upstream selling. This is meaningless in an ideal world so paddle on both sides UX hammer out out of scope, so it's about managing expectations. Digitalize if you want to motivate these clowns, try less carrot and more stick, for one-sheet. Take five, punch the tree, and come back in here with a clear head. Knowledge is power onward and upward, productize the deliverables and focus on the bottom line social currency out of scope we've got to manage that low hanging fruit but can you ballpark the cost per unit for me. Message the initiative we need a recap by eod, cob or whatever comes first. Shotgun approach reach out. Show pony today shall be a cloudy day, thanks to blue sky thinking, we can now deploy our new ui to the cloud . Baseline the procedure and samepage your department ramp up, or can we align on lunch orders, and usabiltiy meeting assassin. Herding cats i am dead inside but this proposal is a win-win situation which will cause a stellar paradigm shift, and produce a multi-fold increase in deliverables and low hanging fruit herding cats nobody's fault it could have been managed better, to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders. The last person we talked to said this would be ready meeting assassin, but what's the status on the deliverables for eow? or I have zero cycles for this, for on this journey, or you better eat a reality sandwich before you walk back in that boardroom. Touch base let's not solutionize this right now parking lot it for message the initiative collaboration through advanced technlogy for drink from the firehose.<br>
            Pulling teeth out of the loop. Curate. Optics this proposal is a win-win situation which will cause a stellar paradigm shift, and produce a multi-fold increase in deliverables cloud strategy strategic fit. Bells and whistles we just need to put these last issues to bed, but peel the onion nor game-plan ladder up / ladder back to the strategy nor we need a recap by eod, cob or whatever comes first i'll book a meeting so we can solution this before the sprint is over. Message the initiative on-brand but completeley fresh sacred cow, nor customer centric. Innovation is hot right now anti-pattern accountable talk we need more paper blue money. Not enough bandwidth feature creep. Table the discussion low-hanging fruit not enough bandwidth five-year strategic plan what the to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders. Where the metal hits the meat this is not the hill i want to die on, for UX show pony, and punter or get all your ducks in a row, yet high touch client. Productize touch base or where the metal hits the meat. Staff engagement. Closer to the metal please advise soonest. Proceduralize guerrilla marketing. Punter can you send me an invite? synergestic actionables so locked and loaded, and churning anomalies. Digitalize highlights driving the initiative forward deploy, for this is meaningless i don't want to drain the whole swamp, i just want to shoot some alligators. Are there any leftovers in the kitchen? we want to see more charts so drink from the firehose.<br>
            On-brand but completeley fresh bleeding edge powerpoint Bunny circle back. I'll book a meeting so we can solution this before the sprint is over. Goalposts good optics so i also believe it's important for every member to be involved and invested in our company and this is one way to do so goalposts into the weeds, or optics. Three-martini lunch. UI translating our vision of having a market leading platfrom pro-sumer software golden goose best practices. One-sheet. Prethink low-hanging fruit this vendor is incompetent nor globalize, so touch base. Quick win can you ballpark the cost per unit for me loop back put a record on and see who dances. Work five-year strategic plan going forward herding cats face time quick-win we need to socialize the comms with the wider stakeholder community. We need to future-proof this organic growth, i'll book a meeting so we can solution this before the sprint is over.')],

            ['title' => 'Carl Sagan Blog', 'post' => string addslashes('A very small stage in a vast cosmic arena radio telescope paroxysm of global death Tunguska event at the edge of forever take root and flourish. Stirred by starlight muse about decipherment hydrogen atoms Orion's sword Drake Equation. Realm of the galaxies something incredible is waiting to be known made in the interiors of collapsing stars dispassionate extraterrestrial observer rings of Uranus great turbulent clouds? Something incredible is waiting to be known invent the universe star stuff harvesting star light dispassionate extraterrestrial observer a mote of dust suspended in a sunbeam bits of moving fluff.<br>
            Ship of the imagination Flatland brain is the seed of intelligence extraordinary claims require extraordinary evidence emerged into consciousness cosmos. Light years dispassionate extraterrestrial observer rich in heavy atoms muse about tingling of the spine the ash of stellar alchemy. Courage of our questions something incredible is waiting to be known hydrogen atoms the only home we've ever known something incredible is waiting to be known courage of our questions.<br>
            Kindling the energy hidden in matter concept of the number one Cambrian explosion corpus callosum cosmos muse about. At the edge of forever the only home we've ever known at the edge of forever finite but unbounded Drake Equation astonishment? Something incredible is waiting to be known courage of our questions a still more glorious dawn awaits great turbulent clouds two ghostly white figures in coveralls and helmets are soflty dancing rich in heavy atoms and billions upon billions upon billions upon billions upon billions upon billions upon billions.')],

            ['title' => 'Post 9', 'post' => 'This is post number nine' ],
            ['title' => 'Post 10', 'post' => 'This is post number ten' ],
            ['title' => 'Post 11', 'post' => 'This is post number eleven' ],
            ['title' => 'Post 12', 'post' => 'This is post number twelve' ]
          ];

          DB::table('posts')->insert($posts);
    }
}
